#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
#
Name     : libopenmpt
Version  : 0.7.2+.autotools
Release  : 1
URL      : https://lib.openmpt.org/files/libopenmpt/src/libopenmpt-0.7.2+release.autotools.tar.gz
Source0  : https://lib.openmpt.org/files/libopenmpt/src/libopenmpt-0.7.2+release.autotools.tar.gz
Summary  : Tracker module player based on OpenMPT
Group    : Development/Tools
License  : BSD-3-Clause BSL-1.0
Requires: libopenmpt-bin = %{version}-%{release}
Requires: libopenmpt-lib = %{version}-%{release}
Requires: libopenmpt-license = %{version}-%{release}
Requires: libopenmpt-man = %{version}-%{release}
BuildRequires : alsa-lib-dev
BuildRequires : buildreq-configure
BuildRequires : doxygen
BuildRequires : perl
BuildRequires : pkgconfig(flac)
BuildRequires : pkgconfig(libmpg123)
BuildRequires : pkgconfig(libpulse)
BuildRequires : pkgconfig(libpulse-simple)
BuildRequires : pkgconfig(ogg)
BuildRequires : pkgconfig(portaudio-2.0)
BuildRequires : pkgconfig(sdl2)
BuildRequires : pkgconfig(sndfile)
BuildRequires : pkgconfig(vorbis)
BuildRequires : pkgconfig(vorbisfile)
BuildRequires : pkgconfig(zlib)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
======
OpenMPT and libopenmpt
======================
This repository contains OpenMPT, a free Windows/Wine-based
[tracker](https://en.wikipedia.org/wiki/Music_tracker) and libopenmpt,
a library to render tracker music (MOD, XM, S3M, IT MPTM and dozens of other
legacy formats) to a PCM audio stream. libopenmpt is directly based on OpenMPT,
offering the same playback quality and format support, and development of the
two happens in parallel.

%package bin
Summary: bin components for the libopenmpt package.
Group: Binaries
Requires: libopenmpt-license = %{version}-%{release}

%description bin
bin components for the libopenmpt package.


%package dev
Summary: dev components for the libopenmpt package.
Group: Development
Requires: libopenmpt-lib = %{version}-%{release}
Requires: libopenmpt-bin = %{version}-%{release}
Provides: libopenmpt-devel = %{version}-%{release}
Requires: libopenmpt = %{version}-%{release}

%description dev
dev components for the libopenmpt package.


%package doc
Summary: doc components for the libopenmpt package.
Group: Documentation
Requires: libopenmpt-man = %{version}-%{release}

%description doc
doc components for the libopenmpt package.


%package lib
Summary: lib components for the libopenmpt package.
Group: Libraries
Requires: libopenmpt-license = %{version}-%{release}

%description lib
lib components for the libopenmpt package.


%package license
Summary: license components for the libopenmpt package.
Group: Default

%description license
license components for the libopenmpt package.


%package man
Summary: man components for the libopenmpt package.
Group: Default

%description man
man components for the libopenmpt package.


%prep
%setup -q -n libopenmpt-0.7.2+release.autotools
cd %{_builddir}/libopenmpt-0.7.2+release.autotools

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1693256708
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1693256708
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libopenmpt
cp %{_builddir}/libopenmpt-0.7.2+release.autotools/LICENSE %{buildroot}/usr/share/package-licenses/libopenmpt/587df320097af9f7b05fa558ec386afdd9d6cdc9 || :
cp %{_builddir}/libopenmpt-0.7.2+release.autotools/src/mpt/LICENSE.BSD-3-Clause.txt %{buildroot}/usr/share/package-licenses/libopenmpt/0206f30bd3a03c6ca719c8ef41f19ca7d30eb8de || :
cp %{_builddir}/libopenmpt-0.7.2+release.autotools/src/mpt/LICENSE.BSL-1.0.txt %{buildroot}/usr/share/package-licenses/libopenmpt/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90 || :
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/openmpt123

%files dev
%defattr(-,root,root,-)
/usr/include/libopenmpt/libopenmpt.h
/usr/include/libopenmpt/libopenmpt.hpp
/usr/include/libopenmpt/libopenmpt_config.h
/usr/include/libopenmpt/libopenmpt_ext.h
/usr/include/libopenmpt/libopenmpt_ext.hpp
/usr/include/libopenmpt/libopenmpt_stream_callbacks_buffer.h
/usr/include/libopenmpt/libopenmpt_stream_callbacks_fd.h
/usr/include/libopenmpt/libopenmpt_stream_callbacks_file.h
/usr/include/libopenmpt/libopenmpt_stream_callbacks_file_mingw.h
/usr/include/libopenmpt/libopenmpt_stream_callbacks_file_msvcrt.h
/usr/include/libopenmpt/libopenmpt_stream_callbacks_file_posix.h
/usr/include/libopenmpt/libopenmpt_stream_callbacks_file_posix_lfs64.h
/usr/include/libopenmpt/libopenmpt_version.h
/usr/lib64/libopenmpt.so
/usr/lib64/pkgconfig/libopenmpt.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/libopenmpt/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libopenmpt.so.0
/usr/lib64/libopenmpt.so.0.4.4

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libopenmpt/0206f30bd3a03c6ca719c8ef41f19ca7d30eb8de
/usr/share/package-licenses/libopenmpt/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90
/usr/share/package-licenses/libopenmpt/587df320097af9f7b05fa558ec386afdd9d6cdc9

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/openmpt123.1
